# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Brewery' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'SnapKit', '~> 5.6.0'
   pod 'Kingfisher', '~> 7.6.1'
  # Pods for Brewery

end
