# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpotifyLoginSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Auth'
  # Pods for SpotifyLoginSampleApp

  target 'SpotifyLoginSampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpotifyLoginSampleAppUITests' do
    # Pods for testing
  end

end
